name: Cross build packages

concurrency:
  group: build-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main-v4.**'
    tags:
      - v*
      - e*
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-20.04
    # prepare source with any OTP version, no need for a matrix
    container: ghcr.io/emqx/emqx-builder/4.4-7:24.1.5-3-ubuntu20.04

    outputs:
      profiles: ${{ steps.set_profile.outputs.profiles}}

    steps:
      - uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0
      - name: set profile
        id: set_profile
        shell: bash
        working-directory: source
        run: |
          if make emqx-ee --dry-run > /dev/null 2>&1; then
            echo "::set-output name=profiles::[\"emqx-ee\"]"
          else
            echo "::set-output name=profiles::[\"emqx\", \"emqx-edge\"]"
          fi
      - name: get_all_deps
        if: endsWith(github.repository, 'emqx')
        run: |
          make -C source deps-all
          zip -ryq source.zip source/* source/.[^.]*
      - name: get_all_deps_ee
        if: endsWith(github.repository, 'enterprise')
        run: |
          echo "https://ci%40emqx.io:${{ secrets.CI_GIT_TOKEN }}@github.com" > $HOME/.git-credentials
          git config --global credential.helper store
          make -C source deps-all
          zip -ryq source.zip source/* source/.[^.]*
      - uses: actions/upload-artifact@v2
        with:
          name: source
          path: source.zip

  windows:
    runs-on: windows-2019
    needs: prepare
    if: endsWith(github.repository, 'emqx')
    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}
        otp:
          - 24.2.1
        exclude:
          - profile: emqx-edge
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: source
        path: .
    - name: unzip source code
      run: Expand-Archive -Path source.zip -DestinationPath ./
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: build
      env:
        PYTHON: python
        DIAGNOSTIC: 1
        PROFILE: emqx
      working-directory: source
      run: |
        erl -eval "erlang:display(crypto:info_lib())" -s init stop
        make ${{ matrix.profile }}-zip
    - name: run emqx
      timeout-minutes: 1
      working-directory: source
      run: |
        ./_build/${{ matrix.profile }}/rel/emqx/bin/emqx start
        Start-Sleep -s 5
        echo "EMQX started"
        ./_build/${{ matrix.profile }}/rel/emqx/bin/emqx stop
        echo "EMQX stopped"
        ./_build/${{ matrix.profile }}/rel/emqx/bin/emqx install
        echo "EQMX installed"
        ./_build/${{ matrix.profile }}/rel/emqx/bin/emqx uninstall
        echo "EQMX uninstaled"
    - uses: actions/upload-artifact@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ matrix.profile }}-windows
        path: source/_packages/${{ matrix.profile }}/.

  mac:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}
        otp:
          - 24.1.5-3
        macos:
          - macos-11
          - macos-10.15
        exclude:
          - profile: emqx-edge
    runs-on: ${{ matrix.macos }}
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: source
        path: .
    - name: unzip source code
      run: unzip -q source.zip
    - name: prepare
      run: |
        brew update
        brew install curl zip unzip gnu-sed kerl unixodbc freetds
        echo "/usr/local/bin" >> $GITHUB_PATH
        git config --global credential.helper store
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.kerl/${{ matrix.otp }}
        key: otp-install-${{ matrix.otp }}-${{ matrix.macos }}
    - name: build erlang
      if: steps.cache.outputs.cache-hit != 'true'
      timeout-minutes: 60
      env:
        KERL_BUILD_BACKEND: git
        OTP_GITHUB_URL: https://github.com/emqx/otp
      run: |
        kerl update releases
        kerl build ${{ matrix.otp }}
        kerl install ${{ matrix.otp }} $HOME/.kerl/${{ matrix.otp }}
    - name: build
      working-directory: source
      run: |
        . $HOME/.kerl/${{ matrix.otp }}/activate
        make ensure-rebar3
        sudo cp rebar3 /usr/local/bin/rebar3
        rm -rf _build/${{ matrix.profile }}/lib
        make ${{ matrix.profile }}-zip
    - name: test
      working-directory: source
      run: |
        set -x
        pkg_name=$(find _packages/${{ matrix.profile }} -mindepth 1 -maxdepth 1 -iname \*.zip)
        unzip -q $pkg_name
        gsed -i '/emqx_telemetry/d' ./emqx/data/loaded_plugins
        ./emqx/bin/emqx start || cat emqx/log/erlang.log.1
        ready='no'
        for i in {1..10}; do
          if curl -fs 127.0.0.1:18083 > /dev/null; then
            ready='yes'
            break
          fi
          sleep 1
        done
        if [ "$ready" != "yes" ]; then
          echo "Timed out waiting for emqx to be ready"
          cat emqx/log/erlang.log.1
          exit 1
        fi
        ./emqx/bin/emqx_ctl status
        if ! ./emqx/bin/emqx stop; then
          cat emqx/log/erlang.log.1 || true
          cat emqx/log/emqx.log.1 || true
          echo "failed to stop emqx"
          exit 1
        fi
        rm -rf emqx
    - uses: actions/upload-artifact@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ matrix.profile }}-${{ matrix.otp }}
        path: source/_packages/${{ matrix.profile }}/.

  linux:
    runs-on: ubuntu-20.04

    needs: prepare

    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}
        package:
          - zip
          - pkg
        otp:
          - 23.3.4.9-3
          - 24.1.5-3
        arch:
          - amd64
          - arm64
        os:
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian11
          - debian10
          - debian9
          - rockylinux8
          - centos7
          - raspbian10
        exclude:
        - package: pkg
          otp: 23.3.4.9-3
        - os: raspbian9
          arch: amd64
        - os: raspbian10
          arch: amd64
        - os: raspbian9
          profile: emqx
        - os: raspbian10
          profile: emqx
        - os: raspbian9
          profile: emqx-ee
        - os: raspbian10
          profile: emqx-ee

    defaults:
      run:
        shell: bash

    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - uses: actions/download-artifact@v2
      with:
        name: source
        path: .
    - name: unzip source code
      run: unzip -q source.zip
    - name: build emqx packages
      env:
        OTP: ${{ matrix.otp }}
        PROFILE: ${{ matrix.profile }}
        PACKAGE: ${{ matrix.package}}
        ARCH: ${{ matrix.arch }}
        SYSTEM: ${{ matrix.os }}
      working-directory: source
      run: |
        ./scripts/buildx.sh \
          --profile "${PROFILE}" \
          --pkgtype "${PACKAGE}" \
          --arch "${ARCH}" \
          --builder "ghcr.io/emqx/emqx-builder/4.4-7:${OTP}-${SYSTEM}"
    - uses: actions/upload-artifact@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ matrix.profile }}-${{ matrix.otp }}
        path: source/_packages/${{ matrix.profile }}/.

  docker:
    runs-on: ubuntu-20.04
    needs: prepare

    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}
        otp:
          - 24.1.5-3
        registry:
          - 'docker.io'
          - 'public.ecr.aws'
        exclude:
          # we don't have an aws ecr repo for enterprise and edge yet
          - profile: emqx-edge
            registry: 'public.ecr.aws'
          - profile: emqx-ee
            registry: 'public.ecr.aws'

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: source
        path: .
    - name: unzip source code
      run: unzip -q source.zip
    - uses: docker/setup-buildx-action@v1
    - uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - uses: aws-actions/configure-aws-credentials@v1
      if: matrix.registry == 'public.ecr.aws'
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Docker login to aws ecr
      if: matrix.registry == 'public.ecr.aws'
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
    - uses: docker/login-action@v1
      if: matrix.registry == 'docker.io'
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ matrix.profile }}
        flavor: |
          latest=${{ !github.event.release.prerelease }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=match,pattern=[v|e](.*),group=1
        labels:
          org.opencontainers.image.otp.version=${{ matrix.otp }}
    - uses: docker/build-push-action@v2
      if: matrix.profile != 'emqx-ee'
      with:
        push: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
        pull: true
        no-cache: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_FROM=ghcr.io/emqx/emqx-builder/4.4-7:${{ matrix.otp }}-alpine3.15.1
          RUN_FROM=alpine:3.15.1
          EMQX_NAME=${{ matrix.profile }}
        file: source/deploy/docker/Dockerfile
        context: source
    - uses: docker/build-push-action@v2
      if: matrix.profile == 'emqx-ee'
      with:
        push: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
        pull: true
        no-cache: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_FROM=ghcr.io/emqx/emqx-builder/4.4-7:${{ matrix.otp }}-alpine3.15.1
          RUN_FROM=alpine:3.15.1
          EMQX_NAME=${{ matrix.profile }}
        file: source/deploy/docker/Dockerfile.enterprise
        context: source

  upload:
    runs-on: ubuntu-20.04

    if: startsWith(github.ref, 'refs/tags/')

    needs: [prepare, mac, linux, docker]

    strategy:
      fail-fast: false
      matrix:
        profile: ${{fromJSON(needs.prepare.outputs.profiles)}}
        otp:
          - 23.3.4.9-3
          - 24.1.5-3
        include:
          - profile: emqx
            otp: windows # otp version on windows is rather fixed

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.profile }}-${{ matrix.otp }}
        path: packages/${{ matrix.profile }}
    - name: install dos2unix
      run: sudo apt-get update && sudo apt install -y dos2unix
    - name: get packages
      run: |
        set -e -u
        cd packages/${{ matrix.profile }}
        for var in $( ls |grep emqx |grep -v sha256); do
          dos2unix $var.sha256
          echo "$(cat $var.sha256) $var" | sha256sum -c || exit 1
        done
        cd -
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: upload aws s3
      run: |
        set -e -u
        if [ "${{ matrix.profile }}"  == "emqx" ];then
            s3dir="emqx-ce"
        else
            s3dir=${{ matrix.profile }}
        fi
        aws s3 cp --recursive packages/${{ matrix.profile }} s3://${{ secrets.AWS_S3_BUCKET }}/${s3dir}/${{ github.ref_name }}
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/${s3dir}/${{ github.ref_name }}/*"
