---

name: Check Elixir Release Applications

on: [pull_request, push]

jobs:
  elixir_apps_check:
    runs-on: aws-amd64
    # just use the latest builder
    container: "ghcr.io/emqx/emqx-builder/5.0-10:1.13.3-24.2.1-1-ubuntu20.04"

    strategy:
      fail-fast: false
      matrix:
        release_type:
          - cloud
          - edge
        package_type:
          - bin
          - pkg
        edition_type:
          - community
          - enterprise
        exclude:
          - release_type: edge
            package_type: bin
            edition_type: enterprise
          - release_type: edge
            package_type: pkg
            edition_type: enterprise

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: ensure rebar
        run: ./scripts/ensure-rebar3.sh 3.16.1-emqx-1
      - name: check applications
        run: ./scripts/check-elixir-applications.exs
      - name: check applications started with emqx_machine
        run: ./scripts/check-elixir-emqx-machine-boot-discrepancies.exs
        env:
          EMQX_RELEASE_TYPE: ${{ matrix.release_type }}
          EMQX_PACKAGE_TYPE: ${{ matrix.package_type }}
          EMQX_EDITION_TYPE: ${{ matrix.edition_type }}

...
