name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        container:
            image: erlang:22.1

        steps:
        - uses: actions/checkout@v1
        - name: Code dialyzer
          run: |
            make xref
            make dialyzer
            rm -f rebar.lock
        - name: Run tests
          run: |
            make eunit
            rm -f rebar.lock
            make ct
            rm -f rebar.lock
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
